### ISSUE TITLE
Please create separate repositories 

### ISSUE THREAD

**Issue by tarsius** [ssm/elisp#2]
Could you please create separate repositories for packages that have nothing to do with one another. That would help users who install packages as git submodules and would also allow me to add the packages to the Emacsmirror. Thanks!

> My lisp code is provided here, such as it is.

If you don't want to do it, then that's fine. But I thought asking would not hurt :-)

**Comment by ssm** [comment]
Good idea.  I'll make separate repositories.

**Comment by tarsius** [comment]
Thanks, looking forward to that.

**Comment by ssm** [comment]
Hello,

vcl-mode is now at https://github.com/ssm/vcl-mode

puppetfile-mode is redundant, the Puppetfile is written in ruby, so ruby-mode should be used instead.

**Comment by tarsius** [comment]
Thanks!
